site_name: Kubemux Documents
site_url: https://kubemux.corvo.fun
repo_url: https://github.com/corvofeng/kubemux
edit_uri: edit/main/docs/


nav:
  - Home: index.md
  - English:
      - Introduction: en/intro.md
      - Why: en/why.md
      - Usage: en/usage.md
      - Example: en/example.md
      - Usage:
      #   - terminator: en/usage/terminator.md
        - kubeconfig: en/usage/kubeconfig.md
        - tmuxinator: en/usage/tmuxinator.md
        - zellij: en/usage/zellij.md
  - 中文文档:
      - 简介: zh/intro.md
      - 为什么: zh/why.md
      - 使用: zh/usage.md
      - 最佳实践: zh/example.md
      - 使用详情:
        - kubeconfig: zh/usage/kubeconfig.md
        - tmuxinator: zh/usage/tmuxinator.md
        - zellij: zh/usage/zellij.md

theme:
  name: "material"
  include_search_page: false
  search_index_only: true
  features:
    - content.code.copy
    - content.code.select
    - content.action.edit
  feature:
    tabs: false
  language: 'en'

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.magiclink
  - toc:
     permalink: True 
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



# markdown_extensions:
#   - admonition
# 

extra:
  disqus: 'kubemux'
  analytics:
    provider: google
    property: G-FVREQ6MGWF
  # search: